### ISSUE TITLE
Expression Tree

### ISSUE THREAD

**Issue by ben1628** [vbilopav/NoOrm.Net#1]
>>Norm will postpone any reads from database until they are needed - allowing you to build expression trees and transformations - before it started fetching any data.<<

Can u provide an example of how to do Linq expression.  Using Blazor, a user can filter what records to get dynamically.  The Where is not known until runtime.  The user may select what fields to get back if that is possible with Norm.

Thanks.

**Comment by vbilopav** [comment]
Try with this article: https://dev.to/vbilopav/norm-data-access-for-net-core-3-fal
