### ISSUE TITLE
Group by not working

### ISSUE THREAD

**Issue by ben1628** [vbilopav/NoOrm.Net#4]
Why something like this always return 0 for the cnt?

        public IAsyncEnumerable<AreaSummary> GetAreaAsync() =>
              _connection.ReadAsync(@"
                        select Description,  count(*) as cnt
                      From A
                      inner join lookup L2
                      on A.areaID= L2.ID
		  Group by  L2.Description

					  order by L2.Description")
                .Select<AreaSummary>()

            .SelectAwait(async u =>
            {
                await Task.Delay(1);
                return u;
            });

and 

    public class AreaSummary
    {
        public string Description { get; set; }

        public int sum { get; set; }

    }

Thanks

**Comment by ben1628** [comment]
Okay, got it figure out.  Have to change the sum to cnt to match with the sql statement

public class AreaSummary
{
    public string Description { get; set; }

    public int cnt { get; set; }

}

**Comment by vbilopav** [comment]
And you don't have to use lowercase to match property name since mapper ignores case. You can Use `Cnt` to make it more consistent.
